### PR TITLE
Mobile Version

### PR DESCRIPTION
**Pull request by abelagza**
## In this milestone I:
- Added instructions to the ReadMe file
- Set up the local environment
- Updated the HTML file and added the following.
    - Works Section
    - About me section
    - Contact me section
- Styled the page using CSS
- Fixed errors

### CODE REVIEW

**Comment by smunozmo** [comment]
Hi @abelagza, 👋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ 

You have submitted a project, that has no register of commits and files changes, this is because the previous branch was merged before approval. Please have a look a this to solve this problem and avoid project invalidations in the future: [Changing the base branch of a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by abelagza** [comment]
The previous branch was already approved.

I made changes without changing to the new branch. When I tried switching to a new one, the command line indicated me to commit first to the old branch, before being able to switch.

image

**Comment by abelagza** [comment]
# In this milestone I:
* Retrieved code from the wrongly modified branch
* Added instructions to the ReadMe file
    Updated the HTML file and added the following.
   Works Section
   About me section
   Contact me section
* Styled the page using CSS
* Fixed linter errors
https://www.loom.com/share/cbd27c64c2944fc7b0771458587a1fd3

**Review by thecodechaser — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @abelagza👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

## Required Changes ♻️
#### I can not highlight the code because this PR does not have code as changed.

- [ ] According to the requirements project technologies should be wrapped in `<ul>` and `<li>.` Please replace the `<div>` and `<p>` with `<li>` and wrap them with `<ul>`

### See the image for reference 

image

- [ ] Please use the correct font size for the project's title and make sure it matches the design

### Your design
image

### Figma design
image

- [ ] Please use the correct font size for "LET'S CONNECT" heading and increase the gap between the social media icons and make sure it matches the design on template.

### Your design
image

### Figma design
image

- [ ] Please use bold font-weight for about section skills headings and make sure it matches the design on the template.

### Your design
image

### Figma design
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by abelagza** [comment]
# In this Milestone I:

> Moved the works items into `ul`'s and `li`'s.
> Rescaled titles and sub-titles to Figma's scaling.
> Corrected gaps.
> Bolded titles on the skills section
> Removed all comment lines.

**Review by micheaol — APPROVED** [review]
# STATUS: APPROVED :green_circle: :clap: 

Hi @abelagza , 

Great work on making the changes requested by the previous reviewer 👏 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 

well-1

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
